In [10]:
import tensorflow as tf
from tensorflow.keras import models,layers
import matplotlib.pyplot as plt
import numpy as np
import keras

In [11]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)
train_batch = train_gen.flow_from_directory(
    directory="/kaggle/input/classfiaction/Dataset/train",
    target_size=(300, 300),
    batch_size=64,
    subset='training',
    class_mode = 'categorical',
    seed=64
)
valid_batch = train_gen.flow_from_directory(
    directory="/kaggle/input/classfiaction/Dataset/val",
    target_size=(300, 300),
    batch_size=64,
    subset='validation',
    class_mode = 'categorical',
    seed=64
)

Found 2607 images belonging to 3 classes.
Found 162 images belonging to 3 classes.


In [12]:
from tensorflow.keras.applications import VGG19
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

In [13]:
base_model = VGG19(weights='imagenet', include_top=False, input_shape=(300, 300, 3))

In [17]:
for layer in base_model.layers:
    layer.trainable = False

x = Flatten()(base_model.output)
x = Dense(256, activation='relu')(x)
x = Dense(128, activation='relu')(x)
output = Dense(3, activation='softmax')(x)  # Replace 'num_classes' with your actual number of classes

In [18]:
model = Model(inputs=base_model.input, outputs=output)
model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [19]:
history1 = model.fit(train_batch,
                    steps_per_epoch=len(train_batch),
                    epochs=30,
                    validation_data=valid_batch,
                    validation_steps=len(valid_batch))

Epoch 1/30


/opt/conda/lib/python3.10/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()
2024-04-26 20:04:21.198195: E external/local_xla/xla/service/slow_operation_alarm.cc:65] Trying algorithm eng11{k2=1,k3=0} for conv (f32[64,64,300,300]{3,2,1,0}, u8[0]{0}) custom-call(f32[64,64,300,300]{3,2,1,0}, f32[64,64,3,3]{3,2,1,0}, f32[64]{0}), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convBiasActivationForward", backend_config={"conv_result_scale":1,"activation_mode":"kRelu","side_input_scale":0,"leakyrelu_alpha":0} is taking a while...
2024-04-26 20:04:21.303270: E external/local_xla/xla/service/slow_operation_alarm.cc:133] The operation took 1.105187227s
Trying algori

25/41 ━━━━━━━━━━━━━━━━━━━━ 21s 1s/step - accuracy: 0.3829 - loss: 4.4787

2024-04-26 20:07:08.314455: E external/local_xla/xla/service/slow_operation_alarm.cc:65] Trying algorithm eng36{k2=3,k3=0} for conv (f32[47,128,150,150]{3,2,1,0}, u8[0]{0}) custom-call(f32[47,128,150,150]{3,2,1,0}, f32[128,128,3,3]{3,2,1,0}, f32[128]{0}), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convBiasActivationForward", backend_config={"conv_result_scale":1,"activation_mode":"kRelu","side_input_scale":0,"leakyrelu_alpha":0} is taking a while...
2024-04-26 20:07:08.445338: E external/local_xla/xla/service/slow_operation_alarm.cc:133] The operation took 1.131016359s
Trying algorithm eng36{k2=3,k3=0} for conv (f32[47,128,150,150]{3,2,1,0}, u8[0]{0}) custom-call(f32[47,128,150,150]{3,2,1,0}, f32[128,128,3,3]{3,2,1,0}, f32[128]{0}), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convBiasActivationForward", backend_config={"conv_result_scale":1,"activation_mode":"kRelu","side_input_scale":0,"leakyrelu_al

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - accuracy: 0.4351 - loss: 3.6393

W0000 00:00:1714162093.758680     118 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1714162159.074354     119 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


41/41 ━━━━━━━━━━━━━━━━━━━━ 325s 5s/step - accuracy: 0.4381 - loss: 3.5999 - val_accuracy: 0.7284 - val_loss: 0.6457
Epoch 2/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 3/30


/opt/conda/lib/python3.10/contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


41/41 ━━━━━━━━━━━━━━━━━━━━ 59s 1s/step - accuracy: 0.7745 - loss: 0.5411 - val_accuracy: 0.6605 - val_loss: 0.7237
Epoch 4/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 239us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 5/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 59s 1s/step - accuracy: 0.8534 - loss: 0.3837 - val_accuracy: 0.7346 - val_loss: 0.5963
Epoch 6/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 7/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 60s 1s/step - accuracy: 0.8639 - loss: 0.3506 - val_accuracy: 0.6605 - val_loss: 0.8858
Epoch 8/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 9/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 59s 1s/step - accuracy: 0.8713 - loss: 0.3383 - val_accuracy: 0.8086 - val_loss: 0.4957
Epoch 10/30
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 269us/step - accuracy: 0.0000e+00

In [29]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
y_pred_prob = model.predict(valid_batch)
y_pred = np.argmax(y_pred_prob, axis=1)
y_true = valid_batch.labels
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
accuracy = accuracy_score(y_true, y_pred)
conf_matrix = confusion_matrix(y_true, y_pred)

print("\nPerformance Metrics:")
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)

3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 923ms/step

Performance Metrics:
Precision: 0.35433292587661586
Recall: 0.36419753086419754
F1 Score: 0.3545407781518892
Accuracy: 0.36419753086419754
Confusion Matrix:
[[29  7 29]
 [16  6 18]
 [22 11 24]]
