In [1]:
import tensorflow as tf
from tensorflow.keras import models,layers
import matplotlib.pyplot as plt
import numpy as np
import keras

2024-04-26 19:37:00.254073: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-26 19:37:00.254179: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-26 19:37:00.395898: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
from tensorflow.keras.applications import VGG19
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

In [3]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Flatten, BatchNormalization,Dropout
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.inception_v3 import InceptionV3
import tensorflow as tf


In [4]:
# Define the image dimensions and batch size
image_size = (224,224)
batch_size = 64

In [5]:
# Data Augmentation

train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

valid_datagen = ImageDataGenerator(rescale=1.0 / 255)

In [6]:
train_data = train_datagen.flow_from_directory(
    directory='/kaggle/input/potatoclass/Dataset/Dataset/train',
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical',
)

validation_data = valid_datagen.flow_from_directory(
    directory='/kaggle/input/potatoclass/Dataset/Dataset/val',
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical',
  )

Found 3257 images belonging to 3 classes.
Found 815 images belonging to 3 classes.


In [7]:
inception_model = InceptionV3(input_shape=(224, 224, 3),
                        include_top=False,
                        weights='imagenet')

for layer in inception_model.layers:
    layer.trainable = False

# Add custom layers
inception_x= inception_model.output

x = Flatten()(inception_x)
x=BatchNormalization()(x)
x= Dense(3, activation='softmax')(x)  # 4 categories

# Create new model
inception_model = Model(inputs=inception_model.input, outputs=x)


87910968/87910968 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [8]:
# Compile the model
inception_model.compile(
    optimizer=Adam(learning_rate=0.0001),
    metrics=['accuracy'],
    loss='categorical_crossentropy'
)

In [9]:
# train the model
inception_model.fit(train_data,
          validation_data=validation_data,
          epochs=30,
          batch_size=100,
          steps_per_epoch=len(train_data),
          validation_steps=len(validation_data),
          #callbacks=[model_checkpoint]
        )


Epoch 1/30


/opt/conda/lib/python3.10/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


 1/51 ━━━━━━━━━━━━━━━━━━━━ 30:56 37s/step - accuracy: 0.3750 - loss: 1.6187

I0000 00:00:1714160274.103591     124 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
W0000 00:00:1714160274.157236     124 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - accuracy: 0.7109 - loss: 0.7464   

W0000 00:00:1714160344.458938     124 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


51/51 ━━━━━━━━━━━━━━━━━━━━ 127s 2s/step - accuracy: 0.7125 - loss: 0.7424 - val_accuracy: 0.7215 - val_loss: 0.6558
Epoch 2/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 3/30


/opt/conda/lib/python3.10/contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


51/51 ━━━━━━━━━━━━━━━━━━━━ 49s 831ms/step - accuracy: 0.8913 - loss: 0.2776 - val_accuracy: 0.8748 - val_loss: 0.3131
Epoch 4/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 5/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 49s 826ms/step - accuracy: 0.9190 - loss: 0.2283 - val_accuracy: 0.9006 - val_loss: 0.2678
Epoch 6/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 7/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 49s 830ms/step - accuracy: 0.9239 - loss: 0.2008 - val_accuracy: 0.9252 - val_loss: 0.2295
Epoch 8/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 9/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 49s 822ms/step - accuracy: 0.9350 - loss: 0.1748 - val_accuracy: 0.9276 - val_loss: 0.2333
Epoch 10/30
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 328us/step - accuracy

In [10]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
y_pred_prob = inception_model.predict(validation_data)
y_pred = np.argmax(y_pred_prob, axis=1)
y_true = validation_data.classes

# Calculate performance metrics
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
accuracy = accuracy_score(y_true, y_pred)
conf_matrix = confusion_matrix(y_true, y_pred)

print("\nInceptionV3 Performance Metrics:")
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)

13/13 ━━━━━━━━━━━━━━━━━━━━ 13s 612ms/step

InceptionV3 Performance Metrics:
Precision: 0.3485686558950565
Recall: 0.3460122699386503
F1 Score: 0.346832303046599
Accuracy: 0.3460122699386503
Confusion Matrix:
[[127  88 111]
 [ 88  61  55]
 [113  78  94]]
